version: "3.8"

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:${BACK_END_PORT}/api/increment"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s
    env_file:
      - .env
    ports:
      - "${BACK_END_PORT}:${BACK_END_PORT}"
    networks:
      - bokman_network

networks:
  bokman_network:
    driver: bridge