version: "3.8"

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:5173"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s
    env_file:
      - .env
    ports:
      - "${FRONT_END_PORT}:5173"
    networks:
      - bokman-network

networks:
  bokman-network:
  