version: "3.8"

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:${FRONT_END_ORIGINAL_PORT}"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s
    env_file:
      - .env
    ports:
      - "${FRONT_END_PORT}:${FRONT_END_ORIGINAL_PORT}"
    networks:
      - bokman_network

networks:
  bokman_network:
    driver: bridge