name: Bokman Front End Action
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - 'main'
      - '!development'
  pull_request:
    branches:
      - 'main'
      - '!development'

jobs:
  build-container:
    runs-on: self-hosted
    steps:
      - name: Echo hello-world
        run: echo Hello bokman
        
      - name: checkout branch
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_SECRET_KEY }}
      
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'

            rm -rf /home/prk/docker/ci-cd-practice/*

            cd /home/prk/docker/ci-cd-practice

            git pull origin main

            docker-compose up -d --build

          EOF
