name: Bokman Front End Action
run-name: ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '!development'
  pull_request:
    branches:
      - 'main'
      - '!development'

jobs:
  build-container:
    runs-on: self-hosted
    steps:
      - name: testing
        run: echo "hee"
        
      - name: Delete code
        run: | 
          rm -rf *
          rm -rf .github
          rm -rf .env
        working-directory: /home/prk/docker/ci-cd-practice

      - name: Pull from main branch
        run: |
          git fetch origin
          git reset --hard origin/main
        working-directory: /home/prk/docker/ci-cd-practice
      
      - name: rebuild and re run image
        run: |
          docker compose down
          docker compose up -d --build
        working-directory: /home/prk/docker/ci-cd-practice