name: Bokman Front End Action
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  handle-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get the last commit message
        run: |
          echo "Last commit message: $(git log -1 --pretty=%B)"
