name: Bokman Front End Action
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - 'main'
      - '!development'
  pull_request:
    branches:
      - 'main'
      - '!development'

jobs:
  bokman-front-end-action:
    runs-on: ubuntu-24.04
    steps:
      - name: Say Hello World
        run: echo "Hello World"
      - name: Say bokman is here
        run: echo "Bokman is here"

