name: Bokman Front End Action
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - 'main'
      - '!development'
  pull_request:
    branches:
      - 'main'
      - '!development'

jobs:
  build-container:
    runs-on: self-hosted
    steps:
      - name: Echo hello-world
        run: echo "Bokman"
